BRIEF_PMT = '''
你是教材设计师。请根据论文为读者建立教学简报，严格区分论文事实、合理假设和待解决问题。
按 textbook-anything 方法：明确可观察学习目标，找出阻塞性先修知识，并为每个缺口安排教学动作。
档位 lite/standard/deep 分别对应一个聚焦单元、连贯章节、深入领域教程；不要因档位省略必要解释。
语言为 {lang}，档位为 {tier}。输出只能是 ``` 包裹的 JSON。
格式：{{"subject":"...","audience":"...","baseline":"明确假设，不把未验证能力写成已掌握","language":"{lang}","tier":"{tier}","learning_outcomes":["..."],"prerequisite_gaps":[{{"knowledge":"...","why_needed":"...","teaching_action":"..."}}],"plan":"..."}}
论文：
[content]\n{paper}\n[/content]
'''

OUTLINE_PMT = '''
你是大学 STEM 教材作者。请把论文重排成读者可以独立学习的教程大纲，而不是复述论文目录。
先安排问题、必要先修、论文继承的方法，再讲核心贡献，最后安排证据、限制和迁移练习。
每章和每节都必须回答一个具体问题；为论文事实与教学示例保持清晰边界。只输出 ``` 包裹的 JSON。
格式：{{"title":"...","preface":"...","chapters":[{{"no":1,"title":"...","purpose":"读者学完能做什么","nodes":[{{"no":1,"title":"...","question":"本节回答什么问题","key_points":["...","..."]}}]}}]}}
论文：[content]\n{paper}\n[/content]
教学简报：[content]\n{brief}\n[/content]
'''

CHAPTER_PMT = '''
你正在编写教程第 {idx} 章《{title}》。面向 {lang} 读者，必须从具体问题开始，定义对象和假设，解释关键推导，给出一个完整例子，
并在章末留下读者可以独立尝试的思考入口。先修内容只讲后文真正需要的部分；论文贡献、继承方法和教学示例要区分。
档位为 {tier}。输出只允许放在 [content] 和 [/content] 之间，不要包围其它说明。
格式方言：{dialect}（Markdown 用标题/列表/LaTeX 数学；LaTeX 用合法 LaTeX；HTML 用 section 内合法 HTML）。
论文：[content]\n{paper}\n[/content]
简报：[content]\n{brief}\n[/content]
大纲：[content]\n{outline}\n[/content]
'''

REVIEW_PMT = '''
审查下面教程章节是否真正完成教学任务。检查：阻塞性先修是否补足；推导是否缺步骤或条件；论文事实是否有越界断言；
例子是否解释方法选择；练习是否可解并能迁移；符号、语言和格式是否一致。若无实质问题，verdict 必须为 PERFECT，否则为 REVISE。
只输出 ``` 包裹的 JSON：{{"verdict":"PERFECT 或 REVISE","comment":"具体位置和修改建议；完美时写 [PERFECT/]"}}
章节：[content]\n{body}\n[/content]
简报：[content]\n{brief}\n[/content]
大纲：[content]\n{outline}\n[/content]
'''

FIX_PMT = '''
根据审查意见修订教程章节。保留已正确的事实、公式和教学目标，只修复意见指出的问题；补全必要条件和推理，避免凭空添加论文没有的实验结果。
输出只允许放在 [content] 和 [/content] 之间，格式方言为 {dialect}。
章节：[content]\n{body}\n[/content]
审查意见：[content]\n{comment}\n[/content]
简报：[content]\n{brief}\n[/content]
大纲：[content]\n{outline}\n[/content]
'''

EXERCISES_PMT = '''
为教程第 {idx} 章《{title}》设计与正文连贯的练习。至少包含一个紧随例题的变式和一个改变条件的迁移题；每题给独立提示和完整推理答案。
题目必须信息充分、可解，答案不得只给最终表达式。不要把未实际运行的数值写成实验结果。只输出 ``` 包裹的 JSON。
格式：{{"exercises":[{{"no":1,"prompt":"...","hint":"...","solution":"..."}}]}}
论文：[content]\n{paper}\n[/content]
简报：[content]\n{brief}\n[/content]
章节大纲：[content]\n{outline}\n[/content]
'''

TEX_STYLE = r'''% Generated by paper2textbook.
\usepackage[a4paper,left=25mm,right=25mm,top=25mm,bottom=24mm]{geometry}
\usepackage{amsmath,amssymb,graphicx,booktabs,xcolor,hyperref}
\usepackage{fontspec,unicode-math}
\setmainfont{TeX Gyre Pagella}
\setmathfont{TeX Gyre Pagella Math}
\definecolor{Accent}{HTML}{315A66}
\usepackage{titlesec}
\titleformat{\section}{\Large\sffamily\bfseries\color{Accent}}{\thesection}{1em}{}
\linespread{1.2}
'''

HTML_TEMPLATE = '''<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title><style>
body{{max-width:900px;margin:0 auto;padding:2rem;color:#202a30;font:18px/1.7 Georgia,serif}}
nav{{background:#f5f7f7;padding:1rem;position:sticky;top:0}} nav a{{margin-right:1rem;color:#315a66}}
h1,h2,h3{{font-family:Arial,sans-serif;color:#315a66}} section{{margin:3rem 0}} .exercise{{background:#f5f7f7;padding:1rem;margin:1rem 0}}
code,pre{{font-family:monospace}} @media(max-width:600px){{body{{padding:1rem;font-size:16px}}}}
</style></head><body><h1>{title}</h1><p>{preface}</p><nav>{nav}</nav>{body}</body></html>'''
